/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  AzTreeItem,
} from './components/tree/az-tree-item';
import {
  AzTree,
} from './components/tree/az-tree';

export namespace Components {
  interface AzTree {
    'addItem': (itemOrCaption: string | AzTreeItem, parent?: AzTreeItem) => Promise<AzTreeItem>;
    'caption': string;
    'roots': AzTreeItem[];
    'selecting': boolean;
  }
  interface AzTreeItem {
    'addItem': (item: string | AzTreeItem) => Promise<void>;
    'caption': string;
    'expanded': boolean;
    'items': AzTreeItem[];
    'level': number;
    'selected': false;
    'tree': AzTree;
  }
}

declare global {


  interface HTMLAzTreeElement extends Components.AzTree, HTMLStencilElement {}
  var HTMLAzTreeElement: {
    prototype: HTMLAzTreeElement;
    new (): HTMLAzTreeElement;
  };

  interface HTMLAzTreeItemElement extends Components.AzTreeItem, HTMLStencilElement {}
  var HTMLAzTreeItemElement: {
    prototype: HTMLAzTreeItemElement;
    new (): HTMLAzTreeItemElement;
  };
  interface HTMLElementTagNameMap {
    'az-tree': HTMLAzTreeElement;
    'az-tree-item': HTMLAzTreeItemElement;
  }
}

declare namespace LocalJSX {
  interface AzTree extends JSXBase.HTMLAttributes<HTMLAzTreeElement> {
    'caption'?: string;
    'roots'?: AzTreeItem[];
    'selecting'?: boolean;
  }
  interface AzTreeItem extends JSXBase.HTMLAttributes<HTMLAzTreeItemElement> {
    'caption'?: string;
    'expanded'?: boolean;
    'items'?: AzTreeItem[];
    'level'?: number;
    'selected'?: false;
    'tree'?: AzTree;
  }

  interface IntrinsicElements {
    'az-tree': AzTree;
    'az-tree-item': AzTreeItem;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


